[package]
name = "gst_test"
version = "0.1.0"
authors = ["Freyr <sky_rider_93@mail.ru>"]

[dependencies]
libc = ""
glib = "0.9"
glib-sys = "0.9"
gobject-sys = "0.9"
gstreamer = "0.15"
gstreamer-sys = "0.8"